version: '3.8'

services:
  python-agents:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - FINANCIAL_DATASETS_API_KEY=${FINANCIAL_DATASETS_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT:-default}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_TRACING_V2=${LANGSMITH_TRACING_V2:-true}
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py
    restart: unless-stopped

  # Optional: Add a database service if needed
  # postgres:
  #   image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/postgres:15
  #   environment:
  #     POSTGRES_DB: agents
  #     POSTGRES_USER: agent_user
  #     POSTGRES_PASSWORD: agent_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
